import Layout from "components/Layout";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

import {default as AppMain} from 'components/App';

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <AppMain>
            <Layout>
                {children}
            </Layout>
        </AppMain>
        </body>
        </html>
    )
}

